parameters:
    blast:

######  Organisms ##########
        Librinfo\CRMBundle\Admin\OrganismAdmin:
            Sonata\AdminBundle\Show\ShowMapper:
                remove:
                    email_history: ~
                add:
                    show_tab_emails:
                        '':
                            email_history:
                                template: LibrinfoEmailCRMBundle:CRUD:show_field_emails_list.html.twig
                                mapped: false
                    _options:
                        tabsOrder:
                            - form_group_alert
                            - form_group_general
                            - show_tab_emails
                            - default

######  Email ##########

        Librinfo\EmailBundle\Admin\EmailAdmin:
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            organisms:
                                type: Blast\BaseEntitiesBundle\Form\Type\SearchIndexAutocompleteType
                                multiple: true
                                required: false
                                _options:
                                    admin_code: librinfo_crm.admin.organism
                            positions:
                                type: Blast\BaseEntitiesBundle\Form\Type\SearchIndexAutocompleteType
                                multiple: true
                                required: false
                            _options:
                                fieldsOrder:
                                    - field_from
                                    - field_to
                                    - field_cc
                                    - field_bcc
                                    - organisms
                                    - positions
                                    - field_subject
                                    - template
                                    - content
                                    - attachments
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    positions:
                        type: doctrine_orm_model_autocomplete
                        multiple: true
                        field_options:
                            property: name
                            admin_code: librinfo_email.admin.email
                            callback: Blast\BaseEntitiesBundle\Admin\SearchIndexEntityAdmin::searchIndexCallback
                    organisms:
                        type: doctrine_orm_model_autocomplete
                        admin_code: librinfo_crm.admin.organism
                        multiple: true
                        field_options:
                            property: 'name'
                            admin_code: librinfo_email.admin.email
                            callback: Blast\BaseEntitiesBundle\Admin\SearchIndexEntityAdmin::searchIndexCallback