Librinfo\EmailBundle\Entity\Email:
    type: entity

    manyToMany:
        positions:
            targetEntity: Librinfo\CRMBundle\Entity\Position
            inversedBy: emailMessages
        organisms:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: emailMessages
